dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
cache:
 directories:
   - $HOME/.cargo
   - $TRAVIS_BUILD_DIR/qtox-updater-genkeys/target
   - $TRAVIS_BUILD_DIR/qtox-updater-sign/target

# regex is for release tags
branches:
  only:
    - master
    - /^v(\d+\.){2}\d+$/

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev

matrix:
  fast_finish: true
  allow_failures:
    - rust: beta
    - rust: nightly

script: "./.travis/build.sh"
